name: Hub Submission Validation (R)

on:
  workflow_dispatch:
  pull_request:
    branches: main
    paths:
      - 'model-output/**'
      - 'model-metadata/*'
      - '!**README**'

jobs:
  validate-submission:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: ghcr.io/hubverse-org/test-docker-hubvalidations:main
      ports:
        - 80
      volumes:
        - ${{ github.workspace }}:/project
    steps:
      - uses: actions/checkout@v4
      - name: Run validations
        run: validate.R . ${{ github.repository }} ${{ github.event.number }}
